all:
	make -C base64
	make -C blowfish
	make -C dir
	make -C file
	make -C hash
	make -C http
	make -C inet
	make -C json
	make -C list
	make -C pid
	make -C proc
	make -C sha1
	make -C sha256
	make -C shm
	make -C socket
	make -C spt
	make -C str
	make -C thread
	make -C url
	make -C wget

clean:
	make -C base64 clean
	make -C blowfish clean
	make -C dir clean
	make -C file clean
	make -C hash clean
	make -C http clean
	make -C inet clean
	make -C json clean
	make -C list clean
	make -C pid clean
	make -C proc clean
	make -C sha1 clean
	make -C sha256 clean
	make -C shm clean
	make -C socket clean
	make -C spt clean
	make -C str clean
	make -C thread clean
	make -C url clean
	make -C wget clean
